---
version: "3"
services:
  backend:
    container_name: node_backend
    image: khaveesh/flashy_backend
    restart: always
    environment:
      WAIT_HOSTS: mongodb:27017
      PORT: 15000
      DBURL: mongodb://mongodb:27017/flashy
      LOG_FILE_NAME: backend.log
    env_file: ~/jwt_secret
    ports:
    - "15000:15000"
    volumes:
    - ~/backend.log:/backend.log
    links:
    - mongodb
    depends_on:
    - mongodb
    networks:
    - node-webapp-network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
    - ~/mongo:/data/db
    ports:
    - "27017:27017"
    networks:
    - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge
