---
- name: Run docker compose
  hosts: aws
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Get the docker compose script
    ansible.builtin.copy:
      src: ./docker-compose.yml
      dest: ./flashy_backend/docker-compose.yml
  - name: Tear down existing services
    docker_compose:
      project_src: ~/flashy_backend
      state: absent
  - name: Create and start services
    docker_compose:
      project_src: ~/flashy_backend
